name: test-main
run-name: test-main
on:
  push:
    branches:
      - main
  schedule:
    # every day at midnight
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    name: run automated tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - run: pip install -e .

      - run: python3 test.py

      - run: bash test.sh
